window.WARDROBE_DATA = [
  { id: 5, name: "black tank", category: "tank", color: "Black", brand: "Free People", season: "summer", capsule: true, type_order: 1, subtype_order: 1 },
  { id: 12, name: "white tank", category: "tank", color: "White", brand: "Uniqlo", season: "summer", capsule: true, type_order: 1, subtype_order: 1 },
  { id: 10, name: "black baby tee", category: "tee", color: "Black", brand: "Urban Outfitters", season: "summer", capsule: true, type_order: 1, subtype_order: 2 },
  { id: 9, name: "white baby tee", category: "tee", color: "White", brand: "Brandy Melville", season: "summer", capsule: true, type_order: 1, subtype_order: 2 },
  { id: 11, name: "yellow baby tee", category: "tee", color: "Yellow", brand: null, season: "summer", capsule: false, type_order: 1, subtype_order: 2 },
  { id: 8, name: "black long sleeve", category: "shirt", color: "Black", brand: "Intimissimi", season: "summer", capsule: false, type_order: 1, subtype_order: 3 },
  { id: 1, name: "blue strapless top", category: "shirt", color: "Sky Blue", brand: "MINKPINK", season: "summer", capsule: true, type_order: 1, subtype_order: 3 },
  { id: 6, name: "blue striped button-down", category: "shirt", color: "Rivera Stripe", brand: "Brochu Walker", season: "summer", capsule: true, type_order: 1, subtype_order: 3 },
  { id: 2, name: "blue striped shirt", category: "shirt", color: "Blue Stripe", brand: "Brochu Walker", season: "summer", capsule: true, type_order: 1, subtype_order: 3 },
  { id: 23, name: "navy long sleeve", category: "shirt", color: "Navy", brand: null, season: "summer", capsule: false, type_order: 1, subtype_order: 3 },
  { id: 7, name: "white button-down", category: "shirt", color: "Salt White", brand: "Brochu Walker", season: "summer", capsule: true, type_order: 1, subtype_order: 3 },
  { id: 20, name: "black midi skirt", category: "skirt", color: "Black", brand: "Brandy Melville", season: "summer", capsule: true, type_order: 2, subtype_order: 1 },
  { id: 19, name: "black pants", category: "pants", color: "Black", brand: "Aritzia", season: "summer", capsule: true, type_order: 2, subtype_order: 1 },
  { id: 26, name: "blue jeans", category: "pants", color: "Blue", brand: "Mom's closet", season: "all-season", capsule: true, type_order: 2, subtype_order: 1 },
  { id: 21, name: "blue midi skirt", category: "skirt", color: null, brand: null, season: "summer", capsule: false, type_order: 2, subtype_order: 1 },
  { id: 18, name: "brown pants", category: "pants", color: "Brown", brand: "Aritzia", season: "summer", capsule: false, type_order: 2, subtype_order: 1 },
  { id: 4, name: "denim shorts", category: "shorts", color: "Ritual", brand: "Citizens of Humanity", season: "summer", capsule: true, type_order: 2, subtype_order: 1 },
  { id: 15, name: "white denim shorts", category: "shorts", color: "White", brand: "Levi's", season: "summer", capsule: true, type_order: 2, subtype_order: 1 },
  { id: 16, name: "white jeans", category: "pants", color: "White", brand: "Mom's closet", season: "summer", capsule: false, type_order: 2, subtype_order: 1 },
  { id: 17, name: "white linen pants", category: "pants", color: "White", brand: "Mom's closet", season: "summer", capsule: true, type_order: 2, subtype_order: 1 },
  { id: 14, name: "dark denim jacket", category: "jacket", color: "Dark Denim", brand: "AllSaints", season: "summer", capsule: true, type_order: 3, subtype_order: 1 },
  { id: 29, name: "brown knitwear jacket", category: "jacket", color: "Brown", brand: null, season: "all-season", capsule: true, type_order: 3, subtype_order: 1 },
  { id: 22, name: "black dress", category: "dress", color: "Black", brand: "Mom's closet", season: "summer", capsule: true, type_order: 4, subtype_order: 1 },
  { id: 3, name: "white dress", category: "dress", color: "Cloud Dancer", brand: "Steve Madden", season: "summer", capsule: true, type_order: 4, subtype_order: 1 },
  { id: 24, name: "black flats", category: "shoes", color: "Black", brand: "Camper", season: "all-season", capsule: true, type_order: 5, subtype_order: 1 },
  { id: 25, name: "silver flats", category: "shoes", color: "Silver Distressed Leather", brand: "Dolce Vita", season: "all-season", capsule: true, type_order: 5, subtype_order: 1 },
];
